const { PubSub, withFilter } = require('apollo-server-express')

const EVENTS = {
  ACCOUNTS_UPDATED: 'ACCOUNTS_UPDATED',
  ACCOUNTS_REMOVED: 'ACCOUNTS_REMOVED',
  ADMIN_UPDATED: 'ADMIN_UPDATED',
  AGGREGATION_UPDATE: 'AGGREGATION_UPDATE',
  ALERTS_UPDATE: 'ALERTS_UPDATE',
  ASSET_UPDATED: 'ASSET_UPDATED',
  ASSETS_UPDATED: 'ASSETS_UPDATED',
  GOALS_UPDATED: 'GOALS_UPDATED',
  PORTFOLIO_UPDATED: 'PORTFOLIO_UPDATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_TOTALS_UPDATED: 'USER_TOTALS_UPDATED',
  USER_SETTINGS_UPDATED: 'USER_SETTINGS_UPDATED',
}

module.exports = {
  pubsub: new PubSub(),
  withFilter,
  EVENTS
}
